# Site settings
title: Dan Cortes | Chicago Digital Strategy & Marketing
email: hi@dancort.es
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dancort.es" # the base hostname & protocol for your site
twitter_username: ddggccaa
github_username:  dgca

# Build settings
markdown: kramdown
highlighter: pygments
sass:
    style: compressed

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      avatar: /assets/img/avatar.jpeg
      favicon: /assets/img/favicon.ico