# Site settings
title: Dan Cortes | Chicago Digital Strategy & Marketing
email: hi@dancort.es
description: > # this means to ignore newlines until "baseurl:"
  I'm Dan Cortes, a digital strategist, designer and builder. I make 
  pretty things that are terrific to use. Let's work together.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dancort.es" # the base hostname & protocol for your site
twitter_username: ddggccaa
github_username:  dgca

# Build settings
markdown: kramdown
highlighter: pygments
sass:
    style: compressed

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      avatar: /assets/img/avatar.jpeg
      favicon: /assets/img/favicon.ico